version: '3'

services:

    db:
        image: mysql
        volumes:
            - ./mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 33060:3306

    web:
        build: .
        volumes:
            - ./www:/var/www/html
            - ./var/www/cache:/var/www/html/var/cache
            - ./var/www/logs:/var/www/html/var/logs
        restart: always
        ports:
            - 8080:80
        depends_on:
            - db